[project]
name = "sqltyped"
version = "0.1.0"
description = "Generate types from raw SQL queries"
readme = "README.md"
authors = [
    { name = "Tyler Hillery", email = "tyhillery@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "typer>=0.15.1",
]

[project.scripts]
sqlt = "sqltyped.cli:sqltyped"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "coverage>=7.6.10",
    "mypy>=1.14.1",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff>=0.9.3",
]
